soyuz76_portal/fn/urls.py
from django.urls import path
from .views import ExcelUploadFormView, FnReplacementListView , search_fn_replacements, filter_data

app_name = 'fn'

urlpatterns = [
    path('fill_database/', ExcelUploadFormView.as_view(), name='fill_database'),
    # path('fn_replacement_table/', fn_replacement_table, name='fn_replacement_table'),
    path('fn_list/', FnReplacementListView.as_view(), name='fn_list'),
    path('search/', search_fn_replacements, name='search_fn_replacements'),
    path('filter-data/', filter_data, name='filter_data'),
]

soyuz76_portal/instructions/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth import views

soyuz76_portal/pages/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import (
    IndexListView,
    AboutRegistrationView,
    InstructionDetailView,
    InstructionCreateView,
    InstructionDeleteView,
    InstructionUpdateView,
    ProfileDetailView,
    ProfileUpdateView,
    CategoryListView,
    CategoryCreateView,
    InstructionCategoryListView,
    ProfileAdminDetailView,
    PostDetailView,
    PostCreateView,
    EngineerFolderListView,
    PprCreateView,

)
from django.views.generic.edit import CreateView
from user.forms import RegistrationForm

app_name = 'pages'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    # urls страниц инструкций
    path('instructions/<int:pk>', InstructionDetailView.as_view(), name='detail'),
    path('instructions/create', InstructionCreateView.as_view(), name='create'),
    path('instructions/<int:pk>/delete', InstructionDeleteView.as_view(), name='delete'),
    path('instructions/<int:pk>/update', InstructionUpdateView.as_view(), name='update'),
    # urls профиля
    path('profile/<str:username>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<str:username>/admin', ProfileAdminDetailView.as_view(), name='profile_admin'),
    path('profile/<str:username>/edit', ProfileUpdateView.as_view(), name='profile_edit'),

    # Post urls
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/create', PostCreateView.as_view(), name='post_create'),

    # ursl категории
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),

    path('instructions/category/<slug:category_slug>/', InstructionCategoryListView.as_view(), name='instructions_category_list'),

    # urls каталоги
    path('engineer_ppr/', EngineerFolderListView.as_view(), name='engineer_ppr'),
    path('ppr_add/', PprCreateView.as_view(), name='ppr_add'),

    # Логин.
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),

    path('about_registration/', AboutRegistrationView.as_view(template_name='registration/about_registration.html'), name='about_registration'),

    # Логаут.
    path('logout/', LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    # Изменение пароля.
    path('password_change/', PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    # Сообщение об успешном изменении пароля.
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Восстановление пароля.
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля.
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # Вход по ссылке для восстановления пароля.
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля.
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=RegistrationForm,
            success_url=reverse_lazy('pages:about_registration'),
        ),
        name='registration',
    ),
]

soyuz76_portal/soyuz76_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('auth/', include('django.contrib.auth.urls')),
    path('fn/', include('fn.urls', namespace='fn')),
    path('params/', include('parameters.urls', namespace='params')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'

handler403 = 'pages.views.csrf_failure'

handler500 = 'pages.views.server_error'

soyuz76_portal/fn/models.py
from django.db import models

from parameters.models import Regions


class FnReplacement(models.Model):
    name_object = models.CharField(max_length=30,
                                   null=True,)

    sap = models.CharField(max_length=10,
                           null=True)

    legal_entity = models.CharField(max_length=100,
                                    null=True)
    addres_object = models.TextField(max_length=200,
                                     null=True)
    nomer_pos = models.IntegerField(max_length=3,
                                    null=True)
    model_fr = models.CharField(max_length=20,
                                null=True,
                                verbose_name='Модель ФР')
    sn_fr = models.BigIntegerField(max_length=20,
                                   null=True,
                                   verbose_name='Серийный номер ФР')
    sn_fn = models.BigIntegerField(max_length=40,
                                   null=True,
                                   verbose_name='Серийный номер ФН')
    date_fp = models.DateField(null=True)
    replacement_date = models.DateField(null=True)
    regions = models.ForeignKey(
        Regions,
        on_delete=models.CASCADE,
        null=True,
        verbose_name='Регион нахождения объекта'
    )

    class Meta:
        verbose_name = ('График замен ФН')

    def __str__(self):
        return '__all__'

soyuz76_portal/fn/forms.py
from django import forms


class ExcelUploadForm(forms.Form):
    excel_file = forms.FileField(label='Выберите Excel файл')

soyuz76_portal/instructions/forms.py
from django import forms
from .models import Category, Instruction


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'slug']


class InstructionForm(forms.ModelForm):
    class Meta:
        model = Instruction
        fields = ['title', 'content', 'category', 'author', 'file']

soyuz76_portal/fn/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from django.views import View
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, DetailView

from .models import FnReplacement
from .forms import ExcelUploadForm
from parameters.models import Objects
import openpyxl
from datetime import datetime, timedelta
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q


fn_post = FnReplacement.objects.all()

class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser

class ExcelUploadFormView(SuperuserRequiredMixin, View):
    template_name = 'fn/loading_excel.html'

    def get(self, request):
        form = ExcelUploadForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ExcelUploadForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES.get('excel_file')
            if excel_file:
                try:
                    # Получить все записи в таблице FnReplacement
                    fn_replacements = FnReplacement.objects.all()

                    # Удалить каждую запись в цикле
                    for fn_replacement in fn_replacements:
                        fn_replacement.delete()
                    # Погнали перенос данных
                    wb = openpyxl.load_workbook(excel_file, data_only=True)
                    sheet = wb.active
                    records_processed = 0

                    for row in sheet.iter_rows(min_row=2, values_only=True):
                        if len(row) < 9:
                            row += (None,) * (9 - len(row))

                        name_object, sap, legal_entity, addres_object, nomer_pos, model_fr, sn_fr, sn_fn, date_fp, replacement_date = row

                        if date_fp is not None:
                            if isinstance(date_fp, datetime):
                                date_fp = date_fp.date()
                            else:
                                try:
                                    date_fp = datetime.strptime(date_fp, "%Y-%m-%d").date()
                                except ValueError:
                                    date_fp = None  # Устанавливаем значение как None при неверном формате даты

                        if replacement_date is not None:
                            if isinstance(replacement_date, datetime):
                                replacement_date = replacement_date.date()
                            else:
                                try:
                                    replacement_date = datetime.strptime(replacement_date, "%Y-%m-%d").date()
                                except ValueError:
                                    replacement_date = None  # Устанавливаем значение как None при неверном формате даты

                        # Поиск объектов с совпадающим SAP значением
                        matching_objects = Objects.objects.filter(sap=sap)

                        for object_instance in matching_objects:
                            region_instance = object_instance.regions  # Получение связанного региона
                            # Создание объекта FnReplacement с установленным значением regions
                            fn_replacement = FnReplacement(
                                name_object=name_object,
                                sap=sap,
                                legal_entity=legal_entity,
                                addres_object=addres_object,
                                nomer_pos=nomer_pos,
                                model_fr=model_fr,
                                sn_fr=sn_fr,
                                sn_fn=sn_fn,
                                date_fp=date_fp,
                                replacement_date=replacement_date,
                                regions=region_instance  # Устанавливаем регион
                            )
                            fn_replacement.save()
                            records_processed += 1

                        # Если SAP не совпадает, создаем FnReplacement с regions=None
                        if not matching_objects.exists():
                            fn_replacement = FnReplacement(
                                name_object=name_object,
                                sap=sap,
                                legal_entity=legal_entity,
                                addres_object=addres_object,
                                nomer_pos=nomer_pos,
                                model_fr=model_fr,
                                sn_fr=sn_fr,
                                sn_fn=sn_fn,
                                date_fp=date_fp,
                                replacement_date=replacement_date,
                                regions=None  # Устанавливаем regions в None
                            )
                            fn_replacement.save()
                            records_processed += 1

                    return JsonResponse({'message': 'Загрузка данных завершена успешно.'})
                except Exception as e:
                    return JsonResponse({'error': str(e)}, status=500)
            else:
                return JsonResponse({'error': 'Файл не был выбран.'}, status=400)
        else:
            return JsonResponse({'error': 'Неверный формат файла.'}, status=400)



# Общий Mixin для отображения ФН
class CommonViewMixin:
    # Общие методы и атрибуты здесь
    model = FnReplacement
    def get_queryset(self):
        current_date = datetime.now()
        two_months_ago = current_date - timedelta(days=25)

        queryset = self.model.objects.filter(
            replacement_date__isnull=False,
            replacement_date__gte=two_months_ago,
        ).order_by('replacement_date')
        return queryset

        filter_column_name = self.request.GET.get('filter_column_name')
        filter_legal_entity = self.request.GET.get('filter_legal_entity')
        if filter_column_name:
            queryset = queryset.filter(name_object__icontains=filter_column_name)
        if filter_legal_entity:
            queryset = queryset.filter(legal_entity__icontains=filter_legal_entity)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_column_name'] = self.request.GET.get('filter_column_name', '')
        context['filter_legal_entity'] = self.request.GET.get('filter_legal_entity', '')
        context['fn_replacements_page'] = context['page_obj']

        return context


# Передача данных на страницу замены ФН
class FnReplacementListView(CommonViewMixin, ListView):

    template_name = 'base/fn.html'
    context_object_name = 'fn_replacements'
    paginate_by = 10

    def get_queryset(self):
        user_regions = self.request.user.regions.all()  # Получаем все регионы текущего пользователя
        common_queryset = CommonViewMixin().get_queryset()

        if self.request.user.employee_position.name == 'Администратор':
            queryset = common_queryset
        # Фильтруем queryset на основе совпадения регионов пользователя и данных из CommonViewMixin
        else:
            queryset = common_queryset.filter(regions__in=user_regions)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_column_name'] = self.request.GET.get('filter_column_name', '')
        context['filter_legal_entity'] = self.request.GET.get('filter_legal_entity', '')
        context['fn_replacements_page'] = context['page_obj']

        # Добавляем текущего пользователя в контекст
        context['user'] = self.request.user

        return context



def search_fn_replacements(request):
    # Получить параметры поиска из GET-параметров запроса
    search_query = request.GET.get('search_query', '')

    # Выполнить поиск записей в модели FnReplacement на основе поискового запроса
    fn_replacements = FnReplacement.objects.filter(
        Q(name_object__icontains=search_query) |
        Q(legal_entity__icontains=search_query)  # Добавьте другие поля, по которым нужно искать
    ).order_by('replacement_date')

    # Создать объект Paginator с количеством записей на странице равным 100
    paginator = Paginator(fn_replacements, 100)

    # Получить номер текущей страницы из GET-параметра
    page = request.GET.get('page')

    try:
        # Получить объект страницы с номером page
        fn_replacements_page = paginator.page(page)
    except PageNotAnInteger:
        # Если page не является целым числом, отобразить первую страницу
        fn_replacements_page = paginator.page(1)
    except EmptyPage:
        # Если page больше, чем доступное количество страниц, отобразить последнюю страницу
        fn_replacements_page = paginator.page(paginator.num_pages)

    # Определить контекст данных для передачи в шаблон
    context = {
        'fn_replacements_page': fn_replacements_page,
        'search_query': search_query,  # Передача поискового запроса в шаблон
    }

    # Отрендерить HTML шаблон с данными таблицы и результатами поиска
    return render(request, 'base/fn.html', context)


def filter_data(request):
    # Получите параметры фильтрации из POST-запроса
    filter_column_name = request.POST.get('filter_column_name', '')
    filter_legal_entity = request.POST.get('filter_legal_entity', '')
    filter_sap = request.POST.get('filter_sap', '')
    filter_sn_fr = request.POST.get('filter_sn_fr', '')
    filter_sn_fn = request.POST.get('filter_sn_fn', '')

    # Выполните фильтрацию данных на основе полученных параметров
    fn_replacements = FnReplacement.objects.filter(
        name_object__icontains=filter_column_name,
        legal_entity__icontains=filter_legal_entity,

soyuz76_portal/templates/base/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории {{ category.title }}
{% endblock %}
{% block content %}
  <h1 class="text-center">Категория - {{ category.title }}</h1>
  <p class="col-6 offset-3 mb-5 lead text-center">{{ category.description }}</p>
  {% for post in page_obj %}
    <article class="mb-5">  
      {% include "base/instructions_card.html" %}
    </article>   
  {% endfor %}
  {% include "includes/paginator.html" %}
{% endblock %}

soyuz76_portal/templates/base/category_list.html
{% extends "base.html" %}
{% block title %}
  Список категорий инструкций
{% endblock %}
{% block content %}
  <div class="row">
    {% for category in object_list %}
      <div class="col-md-4">
        <div class="category-item">
          {% include "base/category_card.html" %}
        </div>
      </div>

      {% if forloop.counter|divisibleby:3 %}
        <div class="clearfix"></div><br>
      {% endif %}
    {% endfor %}
  </div>
  {% include "includes/paginator.html" %}
{% endblock %}

soyuz76_portal/templates/base/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block title %}
  {% if '/edit/' in request.path %}
    Редактирование публикации
  {% elif "/delete/" in request.path %}
    Удаление публикации
  {% else %}
    Добавление публикации
  {% endif %}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        {% if '/edit/' in request.path %}
          Редактирование публикации
        {% elif '/delete/' in request.path %}
          Удаление публикации
        {% else %}
          Добавление публикации
        {% endif %}
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if not '/delete/' in request.path %}
            {% bootstrap_form form %}
          {% else %}
            <article>
              {% if form.instance.image %}
                <a href="{{ form.instance.image.url }}" target="_blank">
                  <img class="border-3 rounded img-fluid img-thumbnail mb-2" src="{{ form.instance.image.url }}">
                </a>
              {% endif %}
              <p>{{ form.instance.created_at|date:"d E Y" }}
              <h3>{{ form.instance.title }}</h3>
              <p>{{ form.instance.text|linebreaksbr }}</p>
            </article>
          {% endif %}
          {% bootstrap_button button_type="submit" content="Отправить" %}
        </form>
      </div>
    </div>
  </div>
{% endblock %}

soyuz76_portal/templates/base/detail.html
{% extends "base.html" %}
{% block title %}
  {{ instruction.title }} | {% if instruction.location and instruction.location.is_published %}{{ instruction.location.name }}{% else %}Планета Земля{% endif %} |
  {{ instruction.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        {% if instruction.image %}
          <a href="{{ instruction.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ instruction.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ instruction.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not instruction.created_at %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not instruction.category_id %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ instruction.created_at|date:"d E Y, H:i" }} |
            <br>
          </small>
        </h6>
        <p class="card-text">{{ instruction.content|linebreaksbr }}</p>

        {% if user.is_superuser %}
          <div class="mb-2">
            <a class="btn btn-sm text-muted" href="{% url 'pages:update' instruction.id %}" role="button">
              Отредактировать инструкцию
            </a>
            <a class="btn btn-sm text-muted" href="{% url 'pages:delete' instruction.id %}" role="button">
              Удалить инструкцию
            </a>
          </div>
        {% endif %}


        <div>
          {% if instruction.file %}
            <h6>Прикрепленные файлы:</h6>
            <ul>
              <li>
                <a href="{{ instruction.file.url }}" download>Скачать инструкцию</a>
              </li>
            </ul>
          {% endif %}
        </div>

      </div>
    </div>
  </div>
{% endblock %}

soyuz76_portal/templates/base/detail_post.html
{% extends "base.html" %}
{% block title %}
  {{ post.name }} | Посты | {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title">{{ post.name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          {{ post.description }}
        </h6>

        <div>
          {% if post.url %}
            <h6>Ссылка на инструкцию:</h6>
            <a href="{{ post.url }}" target="_blank">Ссылка на обнавленную инструкцию</a>
          {% endif %}
        </div>

        <div>
          <h6>Прикрепленные файлы:</h6>
          {% if post.file %}
            <ul>
              <li>
                <a href="{{ post.file.url }}" download>Скачать инструкцию</a>
              </li>
            </ul>
          {% endif %}
        </div>

        <div class="mb-2">
          <a class="btn btn-sm text-muted" href="#" role="button">
            Редактировать пост
          </a>
          <a class="btn btn-sm text-muted" href="#" role="button">
            Удалить пост
          </a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

soyuz76_portal/templates/base/edit_profile.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}

  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-header">
        Изменение данных пользователя <b>{{ user.username }}</b>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Обновить" %}
        </form>
      </div>
    </div>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      const registrationForm = document.getElementById("registration-form");
      const usernameInput = registrationForm.querySelector('[name="username"]');

      usernameInput.addEventListener("input", function () {
        const usernameValue = usernameInput.value;
        const cyrillicPattern = /[а-яА-Я]/;

        if (cyrillicPattern.test(usernameValue)) {
          usernameInput.setCustomValidity("Логин не должен содержать кириллицу.");
        } else {
          usernameInput.setCustomValidity("");
        }
      });
    });
  </script>
{% endblock %}

soyuz76_portal/templates/base/engineer_folder.html
<!-- engineer_folder_content.html -->
<br>
<h1 style="font-size: 14px">Содержимое папки инженера:</h1>
<ul>
  {% for file in files %}
      <h1>файлы</h1>
    <li>{{ file.name }}</li>
  {% endfor %}
</ul>

soyuz76_portal/templates/base/fn.html
{% extends "base.html" %}
{% block title %}

{% endblock %}
{% block content %}
  <div class="container">
    <h1>График замен ФН</h1>
      </div>
    </form>

    <div class="container-fluid">
        {% include "includes/fn_base_template.html" %}
    </div>
    {% include "includes/paginator.html" with fn_replacements_page=fn_replacements_page %}

{% endblock %}

soyuz76_portal/templates/base/index.html
{% extends "base.html" %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <h4 class="col d-flex justify-content-center">Последние новости</h4>
<br/>
    <ul>
        {% for post in object_list %}

          <div class="col d-flex justify-content-center">
            <div class="card" style="width: 40rem;">
              <div class="card-body">

                <h5 class="card-title">{{ post.name }}</h5>


                <p class="card-text">{{ post.description|truncatewords:10 }}</p>
                {% if post.url %}
                  <a href="{{ post.url }}" target="_blank" class="btn btn-primary">Ссылка на новую инструкцию</a>
                {% endif %}
              </div>
                <h6 class="card-subtitle mb-2 text-muted">
                    <div class="d-flex justify-content-end"> <!-- Добавляем блок справа -->
                        <small>
                            Дата создания {{ post.created_at }}
                        </small>
                    </div>
                </h6>

            </div>

          </div>
            <br>
        {% endfor %}

    </ul>
  {% else %}
    <p>Для доступа к информации необходимо <a href="{% url 'login' %}">авторизоваться</a>.</p>
  {% endif %}
{% endblock %}

soyuz76_portal/templates/base/instructions_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ instruction.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ instruction.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ instruction.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not instruction.created_at %}
            <p class="text-danger">Инструкция снята с публикации админом</p>
          {% endif %}
          От автора <a class="text-muted" href="{% url 'pages:profile' instruction.author %}">@{{ instruction.author.username }}</a>
        </small>
      </h6>
      <p class="card-text">{{ instruction.content|truncatewords:10 }}</p>
      <a href="{% url 'pages:detail' instruction.id %}" class="card-link">Читать полный текст</a>

    </div>
  </div>
</div>

soyuz76_portal/templates/base/list_instructions.html
{% extends "base.html" %}
{% block title %}
  Главная страница
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    <h4>Список инструкций</h4>

    <ul>
      {% for instruction in object_list %}
        {% include "base/instructions_card.html" %}
      {% endfor %}
    </ul>
  {% else %}
    <p>Для доступа к информации необходимо <a href="{% url 'login' %}">авторизоваться</a>.</p>
  {% endif %}
{% endblock %}

soyuz76_portal/templates/base/partial_filtered_data.html
{% for fn_replacement in fn_replacements %}
  <tr>
    <td class="table-body-cell">{{ fn_replacement.name_object }}</td>
    <td class="table-body-cell">{{ fn_replacement.sap }}</td>
    <td class="table-body-cell">{{ fn_replacement.legal_entity }}</td>
    <td class="table-body-cell">{{ fn_replacement.addres_object }}</td>
    <td class="table-body-cell">{{ fn_replacement.nomer_pos }}</td>
    <td class="table-body-cell">{{ fn_replacement.model_fr }}</td>
    <td class="table-body-cell">{{ fn_replacement.sn_fr }}</td>
    <td class="table-body-cell">{{ fn_replacement.sn_fn }}</td>
    <td class="table-body-cell">{{ fn_replacement.date_fp }}</td>
    <td class="table-body-cell">{{ fn_replacement.replacement_date }}</td>
  </tr>
{% endfor %}

soyuz76_portal/templates/base/post_cart.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">

      <h5 class="card-title">{{ posts.name }}</h5>

      <p class="card-text">{{ post.description|truncatewords:10 }}</p>
        <h6 class="card-subtitle mb-2 text-muted">
        <small>
            Дата создания {{ post.created_at}}
        </small>
      </h6>
    </div>
  </div>
</div>

soyuz76_portal/templates/base/ppr.html
{% extends "base.html" %}
{% block title %}
  Страница выгрузки ППР
{% endblock %}
{% block content %}
    <ul>
      {% for file in files %}
        <li>{{ file.file_name }} (Загружено: {{ file.upload_date }})</li>
      {% endfor %}
    </ul>

    <!-- Добавьте кнопку "Загрузить" -->
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:ppr_add' %}">Загрузить ППР</a></button>
    </form>
{% endblock %}