soyuz76_portal/fn/urls.py
from django.urls import path
from .views import ExcelUploadFormView, FnReplacementListView , search_fn_replacements, filter_data

app_name = 'fn'

urlpatterns = [
    path('fill_database/', ExcelUploadFormView.as_view(), name='fill_database'),
    # path('fn_replacement_table/', fn_replacement_table, name='fn_replacement_table'),
    path('fn_list/', FnReplacementListView.as_view(), name='fn_list'),
    path('search/', search_fn_replacements, name='search_fn_replacements'),
    path('filter-data/', filter_data, name='filter_data'),
]

soyuz76_portal/pages/urls.py
from django.urls import path, reverse_lazy, include
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .views import (
    IndexListView,
    AboutRegistrationView,
    InstructionDetailView,
    InstructionCreateView,
    InstructionDeleteView,
    InstructionUpdateView,
    ProfileDetailView,
    ProfileUpdateView,
    CategoryListView,
    CategoryCreateView,
    InstructionCategoryListView,
    ProfileAdminDetailView,
    PostDetailView,
    PostCreateView,
    EngineerFolderListView,
    PprCreateView,

)
from django.views.generic.edit import CreateView
from user.forms import RegistrationForm

app_name = 'pages'

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    # urls страниц инструкций
    path('instructions/<int:pk>', InstructionDetailView.as_view(), name='detail'),
    path('instructions/create', InstructionCreateView.as_view(), name='create'),
    path('instructions/<int:pk>/delete', InstructionDeleteView.as_view(), name='delete'),
    path('instructions/<int:pk>/update', InstructionUpdateView.as_view(), name='update'),
    # urls профиля
    path('profile/<str:username>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<str:username>/admin', ProfileAdminDetailView.as_view(), name='profile_admin'),
    path('profile/<str:username>/edit', ProfileUpdateView.as_view(), name='profile_edit'),

    # Post urls
    path('post/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('post/create', PostCreateView.as_view(), name='post_create'),

    # ursl категории
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='create_category'),

    path('instructions/category/<slug:category_slug>/', InstructionCategoryListView.as_view(), name='instructions_category_list'),

    # urls каталоги
    path('engineer_ppr/', EngineerFolderListView.as_view(), name='engineer_ppr'),
    path('ppr_add/', PprCreateView.as_view(), name='ppr_add'),

    # Логин.
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),

    path('about_registration/', AboutRegistrationView.as_view(template_name='registration/about_registration.html'), name='about_registration'),

    # Логаут.
    path('logout/', LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),

    # Изменение пароля.
    path('password_change/', PasswordChangeView.as_view(template_name='registration/password_change_form.html'), name='password_change'),
    # Сообщение об успешном изменении пароля.
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Восстановление пароля.
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля.
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    # Вход по ссылке для восстановления пароля.
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля.
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path(
        'auth/registration/',
        CreateView.as_view(
            template_name='registration/registration_form.html',
            form_class=RegistrationForm,
            success_url=reverse_lazy('pages:about_registration'),
        ),
        name='registration',
    ),
]

soyuz76_portal/parameters/urls.py
from django.urls import path, include

from .views import UploadExcelView
app_name = 'params'

urlpatterns = [
    path('load_objects/', UploadExcelView.as_view(), name='load_objects'),

]

soyuz76_portal/soyuz76_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('pages/', include('pages.urls', namespace='pages')),
    path('auth/', include('django.contrib.auth.urls')),
    path('fn/', include('fn.urls', namespace='fn')),
    path('params/', include('parameters.urls', namespace='params')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'pages.views.page_not_found'

handler403 = 'pages.views.csrf_failure'

handler500 = 'pages.views.server_error'

soyuz76_portal/templates/includes/category_link.html
{% if instruction.category.slug %}
                <a href="{% url 'pages:instructions_category_list' category.slug %}">
                    {{ category.name }}
                </a>
{% else %}
    <!-- Обработка случая, когда slug отсутствует или пуст -->
    {{ instruction.category.title }}
{% endif %}

soyuz76_portal/templates/includes/comments.html
{% if user.is_authenticated %}
  {% load django_bootstrap5 %}
  <h5 class="mb-4">Оставить комментарий</h5>
  <form method="post" action="{% url 'blog:add_comment' post.id %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Отправить" %}
  </form>
{% endif %}
<br>
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'blog:profile' comment.author.username %}" name="comment_{{ comment.id }}">
          @{{ comment.author.username }}
        </a>
      </h5>
      <small class="text-muted">{{ comment.created_at }}</small>
      <br>
      {{ comment.text|linebreaksbr }}
    </div>
    {% if user == comment.author %}
      <a class="btn btn-sm text-muted" href="{% url 'blog:edit_comment' post.id comment.id %}" role="button">
        Отредактировать комментарий
      </a>
      <a class="btn btn-sm text-muted" href="{% url 'blog:delete_comment' post.id comment.id %}" role="button">
        Удалить комментарий
      </a>
    {% endif %}
  </div>
{% endfor %}

soyuz76_portal/templates/includes/fn_base_template.html
<div class="container">
    <div class="table-responsive">
        <table class="table table-bordered" style="font-size: 14px;">
            <thead>
                <tr>
                    <th>Название объекта</th>
                    {% if request.resolver_match.url_name == 'fn_list' %}
                        <th>SAP</th>
                        <th>Юридическое лицо</th>
                        <th>Адрес объекта</th>
                        <th>Модель ФР</th>
                        <th>Серийный номер ФР</th>
                        <th>Серийный номер ФН</th>
                    {% endif %}
                    <th>Номер кассы</th>
                    <th>Дата замены</th>
                </tr>
            </thead>
            <tbody id="table-body">
                {% for fn_replacement in page_obj %}
                    <tr>
                        <td>{{ fn_replacement.name_object }}</td>
                        {% if request.resolver_match.url_name == 'fn_list' %}
                            <td>{{ fn_replacement.sap }}</td>
                            <td>{{ fn_replacement.legal_entity }}</td>
                            <td>{{ fn_replacement.addres_object }}</td>
                            <td>{{ fn_replacement.model_fr }}</td>
                            <td>{{ fn_replacement.sn_fr }}</td>
                            <td>{{ fn_replacement.sn_fn }}</td>
                        {% endif %}
                        <td>{{ fn_replacement.nomer_pos }}</td>
                        <td>{{ fn_replacement.replacement_date }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

soyuz76_portal/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Союз 76</p>
</footer>

soyuz76_portal/templates/includes/header.html
{% load static %}
<header>
  <style>
    /* Стили для кнопок */
    .btn {
      font-size: 12px; /* Размер шрифта */
      padding: 5px 10px; /* Внутренний отступ кнопок */
    }

    /* Стили для текста внутри кнопок */
    .btn a {
      font-size: 12px; /* Размер шрифта текста внутри кнопок */
    }
    .bodyclass{
        font-size: 8px; /* Размер шрифта текста внутри тела страницы */
    }
  </style>
  <nav class="navbar navbar-light" style="background-color: white">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/logo.png' %}" width="200" height="50" class="d-inline-block align-top" alt="">
      </a>
      {% with request.resolver_match.view_name as view_name %}
      {% if user.is_authenticated %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:category_list' %}">Инструкции</a></button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'fn:fn_list' %}">График замены ФН</a></button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:engineer_ppr' %}">ППР</a></button>
      </div>
      {% if user.employee_position.name == 'Администратор' %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'fn:fill_database' %}">Загрузка графика замен ФН</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'params:load_objects' %}">Загрузка списка объектов</a></button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="#">Пользователи ресурса</a></button>
      </div>
      {% endif %}
      {% if user.employee_position.name == 'Администратор' %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:create' %}">Создать инструкцию</a></button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:create_category' %}">Создать категорию</a></button>
          <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:post_create' %}">Создать пост</a></button>
      </div>
      {% endif %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% if user.employee_position.name == 'Администратор' %}{% url 'pages:profile_admin' user.username %}{% else %}{% url 'pages:profile' user.username %}{% endif %}">
            {{ user.last_name }}
          </a>
        </button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:logout' %}">Выйти</a></button>
      </div>
      {% else %}
      <div class="btn-group" role="group" aria-label="Basic outlined example">
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:login' %}">Войти</a></button>
        <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
            href="{% url 'pages:registration' %}">Регистрация</a></button>
      </div>
      {% endif %}
      {% endwith %}
    </div>
  </nav>
</header>

soyuz76_portal/templates/includes/paginator.html
{% if fn_replacements_page.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if fn_replacements_page.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ fn_replacements_page.previous_page_number }}">
            &lt;&lt;
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ fn_replacements_page.number }}</span>
      </li>
      {% if fn_replacements_page.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ fn_replacements_page.next_page_number }}">
            &gt;&gt;
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ fn_replacements_page.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

soyuz76_portal/templates/includes/post_card.html
<div class="col d-flex justify-content-center">
  <div class="card" style="width: 40rem;">
    <div class="card-body">
      {% if post.image %}
        <a href="{{ post.image.url }}" target="_blank">
          <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ post.image.url }}">
        </a>
      {% endif %}
      <h5 class="card-title">{{ post.title }}</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <small>
          {% if not post.is_published %}
            <p class="text-danger">Пост снят с публикации админом</p>
          {% elif not post.category.is_published %}
            <p class="text-danger">Выбранная категория снята с публикации админом</p>
          {% endif %}
          {{ post.pub_date|date:"d E Y, H:i" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
          От автора <a class="text-muted" href="{% url 'blog:profile' post.author %}">@{{ post.author.username }}</a> в
          категории {% include "includes/category_link.html" %}
        </small>
      </h6>
      <p class="card-text">{{ post.text|truncatewords:10 }}</p>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
      <a href="{% url 'blog:post_detail' post.id %}" class="card-link text-muted">Комментарии ({{ post.comment_count }})</a>
    </div>
  </div>
</div>